let firstName = "Sambhav ";
let lastName = "Saraswat";
let fullName = firstName.concat(lastName);
let lengthOfFN = fullName.length;
let Name1 = "I am Samyak Saraswat";
let replaceName = Name1.replace("Samyak", "Sambhav");
let capitalName = fullName.toUpperCase();
let lowerName = capitalName.toLowerCase();
let Sqrt = Math.sqrt(lengthOfFN);
let maxN = Math.max(lengthOfFN, (lengthOfFN + 12.888897643));
let power = Math.pow(4, 2);
let bigNumber = 344.115223498;
let ToFixed = Number(bigNumber.toFixed(2));
let num1 = 20;
let num2 = 30;
let num1ToString = num1.toString();
let num2ToString = num2.toString();
let typeNumber = 1233;
let IncrementNumber = 1;
let DecrementNumber = 1;
console.clear();
console.log("I am in the console screen");
console.log(firstName);
console.log(lastName);
console.log(fullName);
console.log(lengthOfFN);
console.log(Name1);
console.log(replaceName);
console.log(capitalName);
console.log(lowerName);
console.log(Sqrt);
console.log(Math.floor(maxN));
console.log(power);
console.log(ToFixed);
console.log(num1 + num2);
console.log(num1ToString + num2ToString);
console.log(typeof typeNumber);
IncrementNumber++;
console.log(IncrementNumber);
DecrementNumber--;
console.log(DecrementNumber);